### PR TITLE
Set up reviews database schema

### PR DESCRIPTION
**Pull request by amyyli**
Created db schema for user reviews.
Also removed filter on tasks so we can see ALL tasks on the 'Find' page.
Updated README with contributing team information.

### CODE REVIEW

**Comment by stephantabor** [comment]
hey does it need to keep the 200 lines of comments in revews.js?

**Comment by amyyli** [comment]
@stephantabor Yeah no, I'm going to make another commit later so don't merge this yet.

**Comment by amyyli** [comment]
Cleaned up code and finished GET request for displaying all reviews for specific user.
Not sure if lean() is necessary?

**Comment by amyyli** [comment]
Ugh, had merge conflicts and lots of ugly fixing.

**Comment by amyyli** [comment]
Removed .lean() and $and from 'Review' db routes.

**Comment by RWTreichel** [comment]
The "Files Changed" section might be a bit off. Looks like Cody's profile view commits are being added a second time despite already having his PR accepted. Maybe do a rebase to be extra sure your local repo is up to date.

**Comment by amyyli** [comment]
@meat-and-colonel/owners Merge conflicts resolved.

**Pull request merged**
